# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_address',
            field=models.CharField(default='email@domain.com', max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='postal_address',
            field=models.TextField(default='Postal address'),
        ),
    ]
