# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='to_do_list',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('to_do_time', models.DateTimeField(blank=True, null=True)),
                ('to_do_date', models.DateField(blank=True, null=True)),
                ('to_do_title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
