# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='to_do_list',
            name='to_do_date',
        ),
        migrations.AddField(
            model_name='to_do_list',
            name='to_do_priority',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Normal', 'Normal'), ('Nice to do', 'Nice to do')], default='Normal', max_length=32),
        ),
    ]
