# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20180222_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do_list',
            name='attachment',
            field=models.FileField(default=django.utils.timezone.now, upload_to='static/uploads/'),
            preserve_default=False,
        ),
    ]
