# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_to_do_list_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='attachment',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='to_do_list',
            name='to_do_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='to_do_list',
            name='to_do_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
